package cashier;

import static admin.adminMain.getData;
import config.Session;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import login.login_form;

public class cashier_profile extends javax.swing.JInternalFrame {

    public cashier_profile() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
    }
    
    public void userInfo(int adminID){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new enhance.RoundBorder_g();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        jPanel3 = new enhance.RoundBorder_g();
        name_disp = new javax.swing.JLabel();
        pass_disp = new javax.swing.JLabel();
        id_disp = new javax.swing.JLabel();
        code_disp = new javax.swing.JLabel();
        type_disp = new javax.swing.JLabel();
        status_disp = new javax.swing.JLabel();
        username_disp = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel4 = new enhance.RoundPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(246, 244, 235));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons8-user-100.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 140, 130));

        name.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        name.setText("Name of the User");
        jPanel2.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 300, 40));

        jLabel2.setText("Cashier");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 170, -1));

        username.setText("Username");
        jPanel2.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 170, 20));

        jPanel1.add(jPanel2);
        jPanel2.setBounds(30, 20, 750, 150);

        jPanel3.setBackground(new java.awt.Color(246, 244, 235));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name_disp.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        name_disp.setText("Name:");
        jPanel3.add(name_disp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        pass_disp.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        pass_disp.setText("Password:");
        jPanel3.add(pass_disp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        id_disp.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        id_disp.setText("ID:");
        jPanel3.add(id_disp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        code_disp.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        code_disp.setText("Code:");
        jPanel3.add(code_disp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        type_disp.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        type_disp.setText("Type:");
        jPanel3.add(type_disp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        status_disp.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        status_disp.setText("Status:");
        jPanel3.add(status_disp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        username_disp.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        username_disp.setText("Username:");
        jPanel3.add(username_disp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(52, 73, 85));
        jLabel4.setText("Security");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(52, 73, 85));
        jLabel5.setText("User Information");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 160, 0));

        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("LOGOUT");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 0, 100, 40));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 180, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(120, 160, 131));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons8-edit-15.png"))); // NOI18N
        jLabel8.setText("Edit");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        jPanel1.add(jPanel3);
        jPanel3.setBounds(30, 180, 200, 400);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(52, 73, 85));
        jLabel3.setText("Activity Log");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(240, 180, 310, 40);

        jSeparator1.setBackground(new java.awt.Color(80, 114, 123));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(240, 220, 530, 10);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(240, 230, 530, 350);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        login_form out = new login_form();
        out.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
//        cashier_profile_changePass change = new cashier_profile_changePass(currentUser,getData("u_password","users","u_id", String.valueOf(currentUser)));
//        change.setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        Session sess = Session.getInstance();
        name.setText(sess.getFname()+" "+ sess.getLname());
        username.setText(sess.getCode());
        id_disp.setText("User ID: "+sess.getId());
        name_disp.setText("Name: "+ sess.getFname()+" "+ sess.getLname());
        code_disp.setText("Code: "+ sess.getCode());
        type_disp.setText("Type: "+sess.getType());
        status_disp.setText("Status: "+ sess.getStatus());
        username_disp.setText("Username: "+sess.getUsername());
        pass_disp.setText("Password: "+sess.getPassword());
    }//GEN-LAST:event_formInternalFrameActivated


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel code_disp;
    private javax.swing.JLabel id_disp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel name_disp;
    private javax.swing.JLabel pass_disp;
    private javax.swing.JLabel status_disp;
    private javax.swing.JLabel type_disp;
    private javax.swing.JLabel username;
    private javax.swing.JLabel username_disp;
    // End of variables declaration//GEN-END:variables
}
